fal-ai/fal

- tools/regen_grpc.py
There are some differences given that the structure of the project changed in the migration.
> feat: check in grpc_regen tool

- projects/fal/src/fal/__init__.py
- projects/fal/src/fal/cli.py
In 5 days 6 months: will have passed https://github.com/fal-ai/fal/commit/4ad79858c6734369ba68e0b3d1da484c101578c3
> chore: drop dbt-fal special error messages

- .github/workflows/release.yml
- .github/workflows/release_isolate_proto.yml
this one's the one https://github.com/fal-ai/fal/pull/38
> ci: keep lock changes

- projects/fal/src/fal/app.py
```py
from typing import Any
import fal
from fal.toolkit import Image
from pydantic import BaseModel
class Input(BaseModel):
prompt: str
model: str
class Output(BaseModel):
image: Image
class AnyModelRunner(fal.App):
def setup(self) -> None:
self.models = {}
def provide_hints(self) -> list[str]:
return self.models.keys()
def load_model(self, name: str) -> Any:
from diffusers import DiffusionPipeline
if name in self.models:
return self.models[name]
pipeline = DiffusionPipeline.from_pretrained(name)
pipeline.to("cuda")
self.models[name] = pipeline
return pipeline
@fal.endpoint("/")
def run_model(self, input: Input) -> Output:
model = self.load_model(input.model)
result = model(input.prompt)
return Output(image=Image.from_pil(result.images[0]))
```
> feat: provide runner hints

- projects/fal/src/fal/toolkit/__init__.py
- projects/fal/src/fal/toolkit/optimize.py
Adds support for fal's inference engine bindings (aka spatial optimizer) where it takes a torch module and applies all relevant dynamic compilation and quantization techniques to make it faster out of the box without leaking any of the complexity to the user. 
Example usage:
```py
import fal
import fal.toolkit
from fal.toolkit import Image
from pydantic import BaseModel, Field
class Input(BaseModel):
prompt: str = Field(
description="The prompt to generate an image from.",
examples=[
"A cinematic shot of a baby racoon wearing an intricate italian priest robe.",
],
)
class Output(BaseModel):
image: Image = Field(
description="The generated image.",
)
class RealtimeModel(fal.App):
machine_type = "GPU"
requirements = [
"accelerate",
"transformers>=4.30.2",
"diffusers>=0.26",
"torch>=2.2.0", …
```
> feat: add native support for fal's inference engine bindings

- projects/fal/src/fal/app.py
this is already used internally for some of our real-time APIs from the era when they were manually written, this PR includes it in the `@fal.realtime` logic so clients that use it can automatically enable/disable this metric. 
https://github.com/search?q=org%3Afal-ai%20x-fal-message&type=code
> feat: ability to emit timing metrics per message

- projects/fal/src/fal/api.py
- projects/fal/src/fal/app.py
> refactor: add BaseServable to unify behaviors of Apps and serve functions

- projects/fal/src/fal/api.py
- projects/fal/src/fal/apps.py
- projects/fal/tests/test_apps.py
> fix: respond 404 correctly

- projects/fal/src/fal/__init__.py
- projects/fal/src/fal/toolkit/__init__.py
we probably should do it for more files, but I was getting typing errors
> fix: explicit exports from modules

- projects/fal/openapi-fal-rest/openapi_fal_rest/__init__.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/api/workflows/create_or_update_workflow_workflows_post.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/api/workflows/delete_workflow_workflows_user_id_workflow_name_delete.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/api/workflows/execute_workflow_workflows_user_id_workflow_name_post.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/api/workflows/get_workflow_workflows_user_id_workflow_name_get.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/api/workflows/get_workflows_workflows_get.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/__init__.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/customer_details.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/execute_workflow_workflows_user_id_workflow_name_post_json_body_type_0.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/execute_workflow_workflows_user_id_workflow_name_post_response_200_type_0.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/page_workflow_item.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/typed_workflow.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_contents.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_contents_nodes.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_contents_output.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_detail.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_detail_contents_type_0.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_item.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_node.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_node_type.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_schema.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_schema_input.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/models/workflow_schema_output.py
- projects/fal/openapi-fal-rest/openapi_fal_rest/types.py
- projects/fal/src/fal/flags.py
- projects/fal/src/fal/workflows.py
- projects/fal/tests/test_apps.py
Implements the workflows v1 API.
> feat: local & remote workflows

- projects/fal/tests/test_apps.py
temporarily marking it as flaky as it fails randomly
investigating it
> misc: mark workflow test as flaky

- projects/fal/tests/test_apps.py
This reverts commit af28c394c0e20e8b74909222a728aa3329d9f6e6.
Made it pass with some controller changes.
> Revert "misc: mark workflow test as flaky (#113)"

- projects/fal/README.md
> chore: add gha and pypi badges to README

- projects/fal/src/fal/cli.py
Followup for reverted #118
This is a conventional click approach for shared flags.
Looked into adding tests, but the new approach is declarative in itself, so declarative tests seem redundant (e.g. testing `--help`). We still need real cli tests though (e.g. to make sure things like `fal fn run ...` work), but that is out of scope for this PR and will be done in a followup.
> feat(cli): allow using --debug on any subcommand

- .github/workflows/release.yml
- .github/workflows/release_isolate_proto.yml
See https://github.com/fal-ai/fal/pull/146#issuecomment-2024293079
> fix(ci): install poetry 1.8.2 when releasing packages

- .pre-commit-config.yaml
- projects/fal/poetry.lock
- projects/fal/src/fal/__init__.py
- projects/fal/src/fal/api.py
- projects/fal/src/fal/app.py
- projects/fal/src/fal/auth/__init__.py
- projects/fal/src/fal/cli.py
- projects/fal/src/fal/logging/user.py
- projects/fal/src/fal/toolkit/file/__init__.py
- projects/fal/src/fal/toolkit/file/file.py
- projects/fal/src/fal/toolkit/file/providers/fal.py
- projects/fal/src/fal/toolkit/image/__init__.py
- projects/fal/src/fal/toolkit/image/image.py
- projects/fal/src/fal/toolkit/optimize.py
- projects/fal/src/fal/toolkit/utils/__init__.py
- projects/fal/src/fal/toolkit/utils/download_utils.py
- projects/fal/src/fal/workflows.py
- projects/fal/tests/integration_test.py
- projects/fal/tests/mainify_package/__init__.py
- projects/fal/tests/toolkit/image_test.py
- pyproject.toml
> chore: use ruff

- projects/fal/poetry.lock
- projects/fal/src/fal/_serialization.py
- projects/fal/src/fal/api.py
- projects/fal/src/fal/sdk.py
Same as https://github.com/fal-ai/fal/pull/143 but for LocalHost. E.g. `@fal.function(host=fal.LocalHost())`
> feat(api): support chained exceptions on LocalHost

- .pre-commit-config.yaml
- projects/fal_client/README.md
- projects/fal_client/pyproject.toml
- projects/fal_client/src/fal_client/__init__.py
- projects/fal_client/src/fal_client/auth.py
- projects/fal_client/src/fal_client/client.py
- projects/fal_client/tests/test_async_client.py
- projects/fal_client/tests/test_sync_client.py
stuff we need to do before friday:
some features to make this complete:
> feat: add simple fal_client for sync/async + streaming

- projects/fal/tests/test_apps.py
- projects/fal/tests/test_stability.py
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
> feat: add test to exercise Nomad scheduler

- projects/fal_client/pyproject.toml
Useful for ci and development.
> chore(fal_client): add test and dev extras

- projects/isolate_proto/pyproject.toml
Useful for ci and development.
> chore(isolate_proto): add dev extra

- .pre-commit-config.yaml
- projects/fal/pyproject.toml
- projects/fal/src/fal/__init__.py
- projects/fal/src/fal/_serialization.py
- projects/fal/src/fal/api.py
- projects/fal/src/fal/app.py
- projects/fal/src/fal/auth/__init__.py
- projects/fal/src/fal/auth/auth0.py
- projects/fal/src/fal/auth/local.py
- projects/fal/src/fal/cli.py
- projects/fal/src/fal/exceptions/__init__.py
- projects/fal/src/fal/logging/isolate.py
- projects/fal/src/fal/sdk.py
- projects/fal/src/fal/sync.py
- projects/fal/src/fal/toolkit/file/file.py
- projects/fal/src/fal/toolkit/image/image.py
- projects/fal/src/fal/toolkit/optimize.py
- projects/fal/src/fal/toolkit/utils/download_utils.py
- projects/fal/src/fal/workflows.py
- projects/fal/tests/conftest.py
- projects/fal/tests/integration_test.py
- projects/fal/tests/test_apps.py
- projects/fal/tests/test_stability.py
- projects/fal/tests/toolkit/file_test.py
- projects/fal/tests/toolkit/image_test.py
Turns out I forgot to commit this part the last time 🤦
> chore: don't forget to enable more rules for ruff

- projects/fal/src/fal/flags.py
merge if you think it looks good.
> chore: remove unused flag GATEWAY_HOST

- projects/fal/src/fal/_serialization.py
- projects/fal/tests/test_stability.py
Fixes #212 
Also added a test to make sure exc chaining works as designed.
Kudos @badayvedat for catching and reporting this ❤️
> fix(fal): don't assume rich is installed

- projects/fal/pyproject.toml
- projects/fal/src/fal/api.py
Yanked trash isolate releases, trying to keep this safe until previews are working and I can test this out better.
> fix(fal): backward compatibility with isolate 0.12.7

- projects/fal/tests/test_stability.py
Do we need to keep supporting conda environments?
> tests: mark conda test xfail

- projects/fal/src/fal/utils.py
Leftover from https://github.com/fal-ai/fal/pull/206
> chore(fal): don't runpy.run_path twice

- projects/fal/tests/test_apps.py
Related https://github.com/fal-ai/isolate-cloud/pull/1778
> chore(tests): get rid of kubernetes tests

- projects/fal/tests/test_stability.py
Related https://github.com/fal-ai/isolate-cloud/pull/1778
> chore(test): don't use kubernetes scheduler

- projects/fal/src/fal/cli/parser.py
Currently you get a root parser usage, which is not nice:
```
❯ fal deploy ... --alias
Usage: fal [-h] [--debug] [--pdb] [--cprofile] [--version] command ...
fal: error: unrecognized arguments: --alias
```
and with this PR you'll get:
```
Usage: fal deploy [-h] [--debug] [--pdb] [--cprofile] [--app-name APP_NAME] [--auth {public,private,shared}] [app_ref]
fal deploy: error: unrecognized arguments: --alias
```
> fix(cli): show subparser usage on unrecongnised argument

- projects/fal/src/fal/api.py
> fix(api): don't use isolate exceptions

- projects/fal/tests/test_stability.py
https://github.com/fal-ai/isolate-cloud/pull/1841
> chore: temporary test xfail

- projects/fal/src/fal/app.py
Follow up to https://github.com/fal-ai/fal/pull/235
Sorry for the noise.
> fix(container): Fix app issues

- projects/fal/src/fal/api.py
- projects/fal/src/fal/app.py
- projects/fal/src/fal/sdk.py
Draft that makes stuff like
```
with AppClient.connect(MyApp) as client:
client.health()
client.echo(Input(…))
```
possible.
> feat(fal): add auto-generated AppClient

- projects/fal/src/fal/cli/doctor.py
- projects/fal/src/fal/cli/main.py
A place to have all of our useful info that one might need.
> feat(fal): introduce fal doctor

- projects/fal/src/fal/cli/doctor.py
Leftover from https://github.com/fal-ai/fal/pull/240#discussion_r1640016913
> chore: show more of FAL_KEY

- projects/fal/src/fal/toolkit/file/file.py
- projects/fal/src/fal/toolkit/file/providers/fal.py
- projects/fal/src/fal/toolkit/file/types.py
- projects/fal/tests/test_stability.py
Reconsidered https://github.com/fal-ai/fal/pull/250
> fix: keep both v1 and v2 fal storage repos

- .pre-commit-config.yaml
- projects/fal/src/fal/_serialization.py
- projects/fal/src/fal/apps.py
- projects/fal/src/fal/cli/apps.py
- projects/fal/src/fal/cli/debug.py
- projects/fal/src/fal/cli/deploy.py
- projects/fal/src/fal/cli/keys.py
- projects/fal/src/fal/cli/run.py
- projects/fal/src/fal/cli/secrets.py
- projects/fal/src/fal/exceptions/_base.py
- projects/fal/src/fal/logging/isolate.py
- projects/fal/src/fal/sdk.py
- projects/fal/src/fal/toolkit/file/file.py
- projects/fal/src/fal/toolkit/file/providers/fal.py
- projects/fal/src/fal/toolkit/image/image.py
- projects/fal/src/fal/utils.py
- projects/fal/tests/cli/test_apps.py
- projects/fal/tests/cli/test_auth.py
- projects/fal/tests/cli/test_keys.py
- projects/fal/tests/integration_test.py
- projects/fal/tests/test_stability.py
- projects/fal/tests/toolkit/file_test.py
- projects/fal_client/tests/test_async_client.py
- projects/fal_client/tests/unit/test_client.py
🤦 and I was wondering why formatting was not fixed in PRs
Kudos @mederka
> chore: don't forget ruff-format

- projects/fal/src/fal/toolkit/image/__init__.py
- projects/fal/src/fal/toolkit/image/nsfw_filter/__init__.py
- projects/fal/src/fal/toolkit/image/nsfw_filter/env.py
- projects/fal/src/fal/toolkit/image/nsfw_filter/inference.py
- projects/fal/src/fal/toolkit/image/nsfw_filter/model.py
- projects/fal/src/fal/toolkit/image/nsfw_filter/requirements.txt
- projects/fal/src/fal/toolkit/image/safety_checker.py
> feat(toolkit): add safety_checker

- projects/fal/src/fal/sdk.py
Leftover from https://github.com/fal-ai/fal/pull/293/files
> fix(sdk): default deployment strategy -> recreate

- projects/fal/src/fal/cli/deploy.py
Extract from https://github.com/fal-ai/fal/pull/262 , as that PR has some issues for now.
> fix(deploy): tuple -> Tuple for 3.8 compatibility

- projects/fal/src/fal/toolkit/file/providers/fal.py
- projects/fal/tests/test_stability.py
https://github.com/fal-ai/isolate-cloud/pull/2411
> feat(cdn): auth with tokens and talk directly to cdn

- projects/fal/src/fal/api.py
- projects/fal/src/fal/sdk.py
- projects/fal/tests/test_apps.py
closes FEA-3123
⚠️ DO NOT MERGE UNTIL BACKEND IS DEPLOYED ⚠️
> feat: use new machine_types

- tools/regen_grpc.py
Reverts fal-ai/fal#291
https://github.com/fal-ai/fal/pull/291#issuecomment-2358685164
> Revert "chore: remove regen tool in favor of internal"

- projects/fal/src/fal/app.py
We can also add this to the metrics as suggested by @squat , but we can do that in a followup once we know the best way/format to inject that into other metrics.
> feat(app): introduce version

- .github/workflows/docs.yaml
- projects/fal_client/.gitignore
- projects/fal_client/docs/Makefile
- projects/fal_client/docs/conf.py
- projects/fal_client/docs/fal_client.rst
- projects/fal_client/docs/index.rst
- projects/fal_client/docs/make.bat
- projects/fal_client/docs/modules.rst
- projects/fal_client/pyproject.toml
Some basic boilerplate for now. Getting ready for the upcoming fal_client API features).
> feat(fal_client): generate docs

- projects/fal_client/src/fal_client/__init__.py
- projects/fal_client/src/fal_client/client.py
- projects/fal_client/tests/test_async_client.py
- projects/fal_client/tests/test_sync_client.py
For symmetry with all other clients.
> feat(client): add subscribe/status/result

- projects/fal/src/fal/cli/machine.py
- projects/fal/src/fal/cli/main.py
- projects/fal/src/fal/sdk.py
- projects/fal/tests/test_apps.py
Depends on https://github.com/fal-ai/isolate-cloud/pull/2670
> feat(fal): introduce fal machine kill

- projects/fal/src/fal/container.py
https://github.com/fal-ai/isolate-cloud/pull/2760
> feat(container): support registries

- projects/fal/src/fal/container.py
https://github.com/fal-ai/isolate-cloud/pull/2919
> feat(fal): support image builder

- projects/fal/src/fal/toolkit/file/file.py
> fix: pass real params to File class

- projects/fal/src/fal/api.py
- projects/fal/tests/test_stability.py
> chore(fal): remove unused tomli req

- projects/fal/src/fal/cli/deploy.py
> fix: point to new test env on deploy prints

- projects/fal/src/fal/toolkit/file/providers/fal.py
This is what is causing 422 on multipart in our rest.
> fix(toolkit): don't forget Content-Type header

- projects/fal/pyproject.toml
To work around https://github.com/sphinx-doc/sphinx/issues/13362#issuecomment-2666925178
> fix(docs): pin splinx<8.2.0

- projects/fal/src/fal/cli/apps.py
- projects/fal/src/fal/sdk.py
we need to deploy and then this is ready to go
> feat: include requests info in runners list

- projects/fal/src/fal/toolkit/file/file.py
From https://github.com/fal-ai/fal/pull/422/files#r1960283185
> fix(toolkit): use fallback_save_kwargs for object_lifecycle

- projects/fal/src/fal/logging/isolate.py
This reflects what's going on a bit better.
> chore: improve stage log headers

- projects/fal/pyproject.toml
- projects/fal/src/fal/cli/apps.py
- projects/fal/src/fal/sdk.py
> chore: bump isolate-proto version

- projects/fal/pyproject.toml
- projects/fal/src/fal/api.py
- projects/fal/src/fal/config.py
> fix(fal): fix 3.8 support and deserialization errors

- projects/fal/src/fal/cli/profile.py
> fix: update kay flow to match docs

- projects/fal/src/fal/cli/apps.py
* Default app list to alphabetic by alias
* Add an argument --sort-by-runners to order by number of runners asc
* Add an argument --filter to filter apps by string contained in the alias
> feat: orderinug + filtering of app list

- projects/fal/pyproject.toml
New pydantic release messed us up good https://pypi.org/project/pydantic/
> chore(fal): limit pydantic to < 2.11

- projects/fal/src/fal/sdk.py
One could see errors like this one from any command if there is a leftover `team` in the the config profile.
```
❯ fal team unset
Traceback (most recent call last):
File "/Users/matteo/.pyenv/versions/3.11.4/bin/fal", line 5, in <module>
from fal.cli import main
File "/Users/matteo/Projects/fal-ai/fal/projects/fal/src/fal/__init__.py", line 4, in <module>
from fal.api import FalServerlessHost, LocalHost, cached, function
File "/Users/matteo/Projects/fal-ai/fal/projects/fal/src/fal/api.py", line 657, in <module>
_DEFAULT_HOST = FalServerlessHost()
^^^^^^^^^^^^^^^^^^^
File "<string>", line 4, in __init__
File "/Users/matteo/Projects/fal-ai/fal/projects/fal/src/fal/sdk.py", line 186, in get_default_credentials
team_id = USER.get_account(team)["user_id"] if team else None …
```
> fix: load team id lazilly

- projects/fal/src/fal/apps.py
- projects/fal/src/fal/cli/api.py
> feat: support stream in client

- projects/fal/src/fal/auth/__init__.py
- projects/fal/src/fal/cli/auth.py
- projects/fal/src/fal/logging/__init__.py
- projects/fal/src/fal/logging/user.py
- projects/fal/src/fal/sdk.py
Allows us to better manage resources/imports etc, which is important for pickling any code that might accidentally import this.
> chore(auth): drop global USER instance

- projects/fal/src/fal/auth/__init__.py
- projects/fal/src/fal/cli/auth.py
> refactor: remove reference to UserAccess class from logout / login

- projects/fal/src/fal/apps.py
Ideally we would just have a Client class or even just use fal_client, but this will improve this for now.
> chore: remove global http client

- projects/fal/src/fal/app.py
- projects/fal/tests/test_apps.py
This would currently crash starlette with smth like
```
File "/Users/zhvihti/temp/test_str.py", line 9, in homepage
response.headers['X-Custom-Header'] = '😀'
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "/Users/zhvihti/.local/share/mise/installs/python/3.12.8/lib/python3.12/site-packages/starlette/datastructures.py", line 574, in __setitem__
set_value = value.encode("latin-1")
^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001f600' in position 0: ordinal not in range(256)
```
so we should check and ignore these for now. Users that need to support these could just encode them themselves.
Related https://github.com/encode/starlette/issues/790#issuecomment-667881654
> fix: ignore hints that aren't latin-1 encodable to avoid crashing

- projects/fal/src/fal/api.py
> feat: handle any gpu related error as 503

- projects/fal/tests/test_apps.py
I used the wrong index by mistake
> ci: make sure to use app aliases in tests

- projects/fal/src/fal/container.py
Let backend decide what it wants to use by default.
> feat(container): don't set builder by default

- projects/fal/pyproject.toml
- projects/fal/src/fal/cli/files.py
- projects/fal/src/fal/cli/main.py
- projects/fal/src/fal/files.py
Basic cli utils that allow you to list, download and upload files.
> feat(fal): introduce basic fal files

- projects/fal/src/fal/cli/profile.py
- projects/fal/src/fal/flags.py
This enables us to use testing envs easily
> feat(profile): check for fal host in profiles

- projects/fal/src/fal/_version.py
- projects/fal/src/fal/cli/main.py
> feat: show a warnining about using old fal version

- projects/fal/src/fal/toolkit/exceptions.py
- projects/fal/src/fal/toolkit/kv.py
- projects/fal/tests/test_kv.py
```py
from fal.toolkit.kv import KVStore
def test_kv_store():
kv = KVStore("test")
kv.set("test", "test")
assert kv.get("test") == "test"
assert kv.get("test2") is None
```
> feat: add basic KV system

- projects/fal/src/fal/app.py
at the moment, at the end of the timeout the app silently yields a url that was not passed the health check.
also introduced timeout parameters for consumers of app cleint to have configurable timeouts depending on how long their setup function takes.
also makes the following changes on defaults:
- http timeout: 60 -> 30 seconds
- total timeout 10 -> 60 seconds
- previous one excluding the http timeout in total timeout, new one includes it
- retry interval 01. -> 0.5 seconds
> fix(appclient): bug in timeout

- projects/fal/src/fal/api.py
- projects/fal/src/fal/cli/apps.py
- projects/fal/src/fal/sdk.py
> fix: avoid setting a default for auth-mode for set-rev command

- projects/fal/pyproject.toml
- projects/fal/src/fal/cli/apps.py
- projects/fal/src/fal/sdk.py
> feat: print settings when using set-rev

- projects/fal/src/fal/toolkit/utils/download_utils.py
> feat: mark used weight files

- projects/fal/src/fal/toolkit/file/file.py
> chore: add warning when not passing a request object to upload

- projects/fal/pyproject.toml
To pick up https://github.com/fal-ai/fal/pull/636
> chore: bump isolate-proto to 0.17.0

- projects/fal/src/fal/app.py
People are getting confused where to put what, so lets help them out and support both ways.
> feat(fal.App): support class var configuration
