projects/fal/src/fal/api.py
projects/fal/src/fal/cli.py
projects/fal/src/fal/sdk.py
projects/fal/tests/test_apps.py

Do use defaults for optional values.

feat: adapt fal client to proto changes in max_concurrency setting

---

.github/workflows/container.yml
.github/workflows/release.yml
Dockerfile

This commit adds a new feature to the project that builds a container
for every version. This is helpful for easily running the CLI without
having a local installation of Python, e.g. running the CLI in CI or on
Kubernetes.
With the current GitHub actions setup, a container is built on every
merge to main with the Git SHA as the tag as well as on every trigger of
the `release.yml` workflow, in which case the tag will be the version of
the release.
Images will be pushed to ghcr.io/fal-ai/fal.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

feat: build container for each version of the CLI

---

projects/fal/src/fal/__init__.py
projects/fal/src/fal/app.py
projects/fal/src/fal/cli.py
projects/fal/tests/test_apps.py
projects/fal/tests/test_stability.py

~~mainly for discussions on the idea, not the concrete implementation~~ Let's see if we can get it into a decent state to start using it.
```py
import fal
from fal.toolkit import Image, ImageSizeInput, get_image_size
from pydantic import BaseModel, Field
class InputModel(BaseModel):
prompt: str
seed: int = Field(default=42, ge=0, le=2**32 - 1)
class OutputModel(BaseModel):
images: list[Image]
seed: int
class Text2ImageInputModel(InputModel):
image_size: ImageSizeInput = "square_hd"
class Image2ImageInputModel(InputModel):
image_url: str
strength: float = Field(default=0.5, ge=0.0, le=1.0)
class InpaintingInputModel(InputModel):
image_url: str
mask_url: str
strength: float = Field(default=0.5, ge=0.0, le=1.0)
class StableDiffusion(fal.App, _scheduler="nomad"):
machine_type = "GPU" …
```

feat: `fal.App` for multiple endpoints

---

projects/fal/src/fal/cli.py

```
❯ fal auth login
Open browser automatically ('no' to show URL)? [Y/n]:
✓ Authenticated successfully, welcome!
```
before:
```
❯ fal auth login
Open browser automatically ('no' to show URL)? [Y/n]:
✓ Authenticated successfully, welcome!
Insufficient permissions: Contact the fal team for beta testing at hello@fal.ai
```
*****
This is OK since now Auth0 sends a webhook when a user is registered

fix: stop sending request that ends in error for API users after login

---

.github/workflows/integration_tests.yaml

We want to keep 3.9 compatibility, this is a good way to ensure this.
The recently merged #44 passed probably by chance, since the error was really in the testing environment itself.

ci: run tests with python 3.9

---

projects/fal/src/fal/app.py

To be used with the `exposed_port` apps, which we can not guarantee the order of the schema fields. With the `_mark_order_openapi` function we guarantee that the order will be preserved.
Example usage:
```py
import fal
from fal.app import _mark_order_openapi
@fal.function(..., exposed_port=8080, metadata=_mark_order_openapi(openapi_spec))
def test():
...
```

chore: move mark openapi spec to global module

---

projects/fal/src/fal/_serialization.py
projects/fal/src/fal/cli.py

stuff that works with `python t.py` doesn't work when we do `fal fn run` / `fal fn serve` because the path handlers need to be manually updated.

fix: include serialization listeners when serving/running from CLI

---

projects/fal/poetry.lock
projects/fal/pyproject.toml
projects/fal/src/fal/__init__.py
projects/fal/src/fal/app.py
projects/fal/src/fal/apps.py
projects/fal/tests/test_apps.py

Building realtime apps without these are super hard and makes the code look terrible, this basically abstracts all the required stages for the user and lets them just define the inference behavior similiar to how the regular HTTP stuff works. Real world example of this code clutter: https://github.com/fal-ai/serverless-registry/blob/9f49dad913e10404a647eff3f7fa2f2e79e7f721/registry/image/lcm/inference.py#L292-L431
example:
```py
class RealtimeApp(fal.App, _scheduler="nomad"):
requirements = ["websockets", "msgpack"]
def setup(self):
pass
@fal.endpoint("/")
def generate(self, input: Input) -> Output:
return Output(text=input.prompt)
@fal.endpoint("/ws", is_websocket=True)
async def generate_ws(self, websocket: WebSocket) -> None:
await websocket.accept()
for _ in range(3):
await …
```

feat: add realtime building blocks to the SDK

---

projects/fal/src/fal/cli.py

this does not work since we added min concurrency and since we have 3 knobs to move (max-concurrency, min-concurrency, max-multiplexing) it is not clear what we are changing by doing `scale app 3`. let's just drop it and use `update` with flags

fix: drop fal alias scale command

---

projects/fal/src/fal/app.py
projects/fal/src/fal/apps.py
projects/fal/tests/test_apps.py

Dynamic batching allows us to utilize the GPU in its full capacity when we already have the inputs lined up and we know it can be combined, which boosts the total throughput by up to 1.5x-2x depending on the models (e.g. for sd-turbo at 1 step, `dynamic_batching=4` enables per image latency to go from 40ms to 25ms).
Programatic hinting of batch sizes:
```py
class ImageToImageInput(BaseModel):
prompt: ...
negative_prompt: ...
def can_batch(self, other: ImageToImageInput) -> bool:
return (
self.prompt == other.prompt
and self.negative_prompt == other.negative_prompt
and self.image_size == other.image_size
[...]
and self.loras == other.loras
and self.model_name == other.model_name
)
```
Handling in the inference functions
```py
class ImageToImage(fal.App): …
```

feat: add dynamic batching to realtime SDK

---

projects/fal/src/fal/app.py
projects/fal/tests/test_apps.py

Optimizes message delivery and handling (adds around ~5-6 FPS to the realtime turbo demo) by not blocking the event loop when processing the inputs and continously receiving/sending stuff in the background. Also changes dynamic batching API to give a hint of `current_batch_size` so the inputs themselves can also decide how long of a batch they permit.

perf: optimize message delivery and give bs hints

---

projects/fal/src/fal/sdk.py

ref: https://stackoverflow.com/questions/64227270/use-retrypolicy-with-python-grpc-client

feat: add retry config for UNAVAILABLE errors

---

projects/fal/src/fal/auth/__init__.py
projects/fal/src/fal/auth/auth0.py

It seems sometimes `iat` (issued at) value from auth0 id token has a slightly-later value than it should, so we are adding some leeway to let those pass.

feat: add leeway to id_token check to account for clock skew

---

projects/fal/src/fal/cli.py

Currently if you want to use `--debug`, you have to specify it right after `fal` and any other place will result in an error, e.g.
```
$ fal function serve ... --debug
No such option: --debug
```
This PR allows it to be used with any subcommand.

feat(cli): add ability to use --debug on all levels

---

.github/workflows/integration_tests.yaml

We already checked out our current branch in a previos step, so there is no reason to clone this again, especially since the new cloned dir is not used anyway.
Also made that checkout(fetch) step use a shallow clone.

ci: don't clone github.com/fal-ai/fal

---

.github/workflows/integration_tests.yaml

Right now we only run tests on PRs, but it is useful to also run them on main and on schedule, so internal and external contributors could have a frame of reference for their changes and general health of the project (e.g. some 3rd party dependency updated and broke something or our service broke over the weekend/night etc).
Note that at any given moment there will only be 1 worker running integration tests for commits from main, so we shouldn't waste much resources even during fast merge pace.

ci: run integration tests on main and schedule

---

projects/fal/src/fal/cli.py

This reverts commit 72cd669dc0b10d744d8f0014506eb42cf874ea78.
```
fal fn serve file.py App --alias some-alias
Usage: fal [OPTIONS] COMMAND [ARGS]...
Try 'fal --help' for help.
Error: No such option: --alias
(fal) 
```

Revert "feat(cli): add ability to use --debug on all levels (#118)"

---

projects/fal/src/fal/cli.py

For example, when you don't specify a subcommand you get a `0` printed, which is coming from a click's `Exit` exception:
```
$ fal auth
Usage: fal auth [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
login
logout
0
```

fix(cli): don't try to print typical cli/click exceptions

---

projects/fal/src/fal/auth/auth0.py

I noticed that all my commands were super slow (like `fal auth` that should just error-out was taking 6 seconds to run) and upon investigation saw that my `access_token` was always considered expired. It turned out that it was just a typo that made a leeway be 1800 minutes instead of 30 minutes like comment suggests.

fix(auth): fix typo in token expiration leeway

---

projects/fal/src/fal/__main__.py
projects/fal/src/fal/cli.py

This allows people to run fal like so `python -m fal`. I don't think anyone was using `python -m fal.cli`, but have to clarify that this patch makes it no longer work, which could be considered a breaking change.
Also it is common for people to expect a `__main__.py` to be present, so this should be useful for anyone lurking around.

fix(cli): use conventional __main__.py

---

projects/fal/pyproject.toml

Currently if you install fal in a fresh environment, `fal auth login` will work, but you'll get a message from pyjwt:
```
$ fal auth login
Open browser automatically ('no' to show URL)? [Y/n]: y
✓ Authenticated successfully, welcome!
The JWK Set did not contain any usable keys. Perhaps 'cryptography' is not installed?
```
and any other fal commands after that will tell you that you are not authenticated. This is because of a missing `[crypto]` extra.

fix(deps): install pyjwt[crypto] for auth to work out-of-box

---

projects/fal/src/fal/auth/auth0.py
projects/fal/src/fal/console/ux.py

The prompt is unnecessary, we should just try opening a browser automatically.
Currently the URL tells me to check the code in CLI, which is not shown to me if `webbrowser.get()` was able to find a browser. Also then `open_new_tab` is not really guaranteed to work, so we are better off just always showing the URL as well.
Also it is obvious that the url is a bit too long to comfortably transfer to another device by hand, but I do understand that it is a temporary technical limitation. Just trying to make things clearer from cli side as much as possible.

fix(auth): always try to open browser but also show url and code

---

projects/fal/src/fal/_serialization.py
projects/fal/src/fal/api.py
projects/fal/src/fal/cli.py
projects/fal/src/fal/exceptions/__init__.py
projects/fal/src/fal/exceptions/handlers.py

This patch adds support for chained exceptions and utilizes those to provide a more seamless experience for both cli and api users by providing them with original exceptions and their tracebacks.
This likely makes isolate's `stringized_traceback` obsolete.
For example:
```python
import fal
class FooException(Exception):
pass
class BarException(Exception):
pass
def bar():
raise BarException("bar")
def foo():
try:
bar()
except Exception as exc:
raise FooException("foo") from exc
@fal.function()
def mytest():
foo()
print(str(2*2))
if __name__ == "__main__":
mytest()
```
running it through API we now we'll get (note that not only traceback is present but also `__cause__` is correctly set):
```
Traceback (most recent call last):
File "/Users/efiop/git/efiop/ui-comp/fal/exc_chain.py", line 15, …
```

feat(api): improve handling of user exceptions

---

projects/fal/src/fal/api.py
projects/fal/src/fal/logging/isolate.py

Provides consistent output between remote and local hosts.
Before:
After:
which is consistent with remote.
Pre-requisite for next steps in cli's ux.

fix(api): use same logger for LocalHost

---

projects/fal/src/fal/logging/isolate.py

It is unexpected that we print all of them to stdout and also prepend a bunch of logging information. This should be seamless for the user most of the time.
Before:
After:
Same for `fal fn run`.

fix(ux): print user messages as is

---

.github/workflows/integration_tests.yaml
projects/fal/src/fal/_serialization.py
projects/fal/tests/conftest.py
projects/fal/tests/integration_test.py

Our tests use network a lot, so it makes sense to run them in parallel. E.g. now down to 5 minutes from seeing stuff as much as 29 minutes.

chore: try using pytest-xdist and XS machines to speedup tests

---

projects/fal/src/fal/toolkit/file/file.py
projects/fal/src/fal/toolkit/image/image.py

On pydantic v1 (v2 seems to work fine), `PrivateAttr`s initialization is pretty intricate and our pickling (not us but cloudpickle) in an unclear way seems to be messing with the order of attribute setting and results in private attrs finding their way into `__dict__` of the model and so into its `dict()` as well, even though they are also in `__private_attributes__`. I dug around, but I think in interest of time we are better off not using them for now. General feeling is that `PrivateAttr`s are not too common (we don't use it anywhere else in the whole org) and, esp in v1, are pretty fragile/buggy (https://github.com/pydantic/pydantic/issues/7142, https://github.com/pydantic/pydantic/discussions/3480).
We kinda made this work before …

fix(toolkit): use hidden bytes/str Field instead of PrivateAttr with custom types

---

projects/fal/pyproject.toml
projects/fal/src/fal/api.py

This commit adds basic Prometheus instrumentation of the HTTP server of
all applications served with `serve=True`. This lets us conveniently
monitor how models are performing.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

feat: instrument served apps with Prometheus metrics

---

projects/fal/src/fal/api.py
projects/fal/tests/test_apps.py

Since fastapi could work with any pydantic version, we are better off being more specific.
Followup for https://github.com/fal-ai/fal/pull/167

fix(api): specify pydantic version in SERVE_REQUIREMENTS

---

.github/workflows/release.yaml

Allows us to not use tokens/secrets at all.
See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi

chore(gha): use OICD for pypi releases

---

projects/fal/src/fal/exceptions/handlers.py

E.g. previously one would get
```
Error while serializing the given object
```
and now
```
Error while serializing the given object: Can't pickle <cyfunction ConstrainedList.list_length_validator at 0x110f544b0>: it's not the
same object as pydantic.types.ConstrainedList.list_length_validator
```
which is much more useful (obviously pickle errors are still obscure as hell, but that's a different topic).

fix(fal): show cause in cli

---

projects/fal/src/fal/api.py

`gather` doesn't cancel other tasks automatically, e.g. causing metrics server to keep running if user app failed to `setup()`.
Caused by #31

fix(api): stop other servers if one exited

---

projects/fal/src/fal/api.py
projects/fal/src/fal/exceptions/__init__.py
projects/fal/src/fal/exceptions/_base.py
projects/fal/src/fal/exceptions/auth.py
projects/fal/src/fal/exceptions/handlers.py
projects/fal/src/fal/workflows.py

This was a little bit more involved before cloudpickle migration, as you had to put `@mainify` everywhere. Now we can comfortably do that and leverage this in error handling (e.g. see us passing through our own exceptions).

fix(fal): inherit all exceptions from FalServerlessException

---

projects/fal/pyproject.toml
projects/fal/tests/toolkit/image_test.py

From tests it seems the storage.googleapis.com link was slow to respond some times. (I am guessing we abused it)

fix: use non-protected url

---

projects/fal/tests/test_stability.py

Reverts fal-ai/fal#193
With https://github.com/fal-ai/isolate-cloud/pull/1689 merged and deployed, we can remove xfail.

Revert "test: mark test_missing_dependencies xfail for SerializationError"

---

projects/fal/README.md

Just basic stuff for our internal and external users.

chore(readme): add basic contributing section

---

projects/fal/src/fal/api.py
projects/fal/src/fal/app.py

Introducing default `/health` endpoint that will by default return `{}` and can be extended by user-provided info using `fal.App.health()` method. This endpoint could also be used as a default endpoint to try connecting to, to know if the app is running.

feat(App): introduce /health endpoint

---

projects/fal/pyproject.toml

This is too strict and creates conflicts with other packages like poetry.

chore(fal): unpin packaging

---

projects/fal/src/fal/toolkit/utils/download_utils.py

Added a new optional parameter verbose to the `download_file` function. This parameter, when set to `True`, will print messages to the console indicating the download progress. By default, it is set to `True`.
Wrapped the call to `_get_remote_file_properties` in a `try-except` block. This is to handle any exceptions that might occur during the call (e.g., a non-existing URL) and raise a `DownloadError` with a descriptive message.
I would be happy to replace this with a logger in the future to make it more clear.

feat(toolkit): add custom headers param to download utilities

---

.gitignore
projects/fal/src/fal/__init__.py
projects/fal/src/fal/api.py
projects/fal/src/fal/container.py
projects/fal/tests/test_apps.py
projects/fal/tests/test_stability.py

Add bare-bone APIs for experimental container support.
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

feat(container): Add initial APIs

---

projects/fal/pyproject.toml

Strictly speaking we should always generate python code with the same version of grpc that we will be using it with. Mixing and matching can cause unpredictable behaviour.
Related https://github.com/fal-ai/fal/pull/231
Related https://github.com/fal-ai/isolate/pull/139

chore(fal): bump grpcio/isolate/isolate_proto

---

.github/workflows/integration_tests.yaml
projects/fal/pyproject.toml
projects/fal/src/fal/toolkit/file/providers/fal.py
projects/fal/tests/toolkit/file_test.py

fix: ensure all uploads avoid clashes and respect the extension

---

projects/fal/src/fal/api.py

Right now, multi-line tracebacks are spread out and ingested
independently into the underlying logging system. This makes it hard to
retrieve the entirety of a traceback without some hacky heuristics. To
enable easy searching and retrieval of tracebacks, we catch all uncaught
exceptions and log them as JSON, this way the whole traceback is in one
single JSON line, which can be extracted by looking at the `traceback`
key.
An alternative would be to print the traceback in `unicode_escape`
encoding and then to to decode the string during log retrieval. This
would remove the need for a JSON wrapping.
Signed-off-by: squat <lserven@gmail.com>

feat: wrap tracebacks in JSON for easy detection

---

projects/fal/tests/test_apps.py

This commit adds a new test to verify that the JSON-formatted traceback
wrapping is working end-to-end. This proves that
https://github.com/fal-ai/isolate-cloud/pull/1925 and
https://github.com/fal-ai/fal/pull/245 all work.
Note that for the purpose of testing, we add a temporary commit pointing
the tests at the temporary preview deployment: api.pr1925.shark.fal.ai.
We will remove this commit before merging.

add traceback logging test

---

projects/fal/src/fal/cli/deploy.py
projects/fal/tests/test_apps.py

```
$ fal deploy t/app.py::jokes_standard --app-name=jokeversion --auth shared
Registered a new revision for function 'jokeversion' 
(revision='ce7539e5-4325-435a-bf17-d1e012bea7f8').
URL: https://fal.ai/models/mederka/jokeversion
```

feat: print playground url on deploy

---

projects/fal/tests/test_stability.py

Depends on https://github.com/fal-ai/isolate-cloud/pull/1976

fix(test): chore: use v2.fal.media instead of fal-cdn.fly.dev

---

projects/fal/src/fal/toolkit/file/providers/gcp.py
projects/fal/src/fal/toolkit/file/providers/r2.py
projects/fal/tests/toolkit/file_test.py

This fixes the overlap issues in cases where you try to upload 2 files with the same name.
Note that I removed the tests introduced in #115 , because the approach here is super obvious/declarative and it is just not worth the overhead of using real storage providers and maintaining that, every test like that is making our test suit more flaky and slow, forcing us to be more sloppy.
We could add unit tests for something like `self._get_key`, but again, considering how straightforward this is - probably not worth it.
Regarding the old fal-cdn using file extension - that will come as a revival of https://github.com/fal-ai/fal-cdn/pull/4 in a separate PR (https://github.com/fal-ai/fal-cdn/pull/23)

fix(toolkit): use random string when uploading to gcp/r2

---

projects/fal/src/fal/logging/isolate.py

Some basic highlights to start with, kinda following the style of flyctl since it is so nice :)
We still hang without anything when serializing/connecting locally and some of the user logs (like the ones about compressing the env) are not ideal, but those need a bit more work, so this is just a start.

feat: highlight build/prepare/run stages in remote isolate logs

---

projects/fal/src/fal/toolkit/utils/download_utils.py

Make sure our files/directories are created in a temporary location that is on the same filesystem as the target to avoid unnecessary copies across filesystems and to make it possible to (semi)atomically move them into place using `os.rename`.
I don't have good examples yet, but this might make some of our apps faster because they used to clone to tempfs but then shutil.move (which copies across fs) to a data fs. Obviously for that the apps would need to be redeployed.

fix(toolkit): fix race conditions in download_utils

---

projects/fal/src/fal/api.py

The default uvicorn keepalive timeout is 5s.
This will allow servers connecting to served fal apps to use longer
keepalives and reuse TCP connections, avoiding extra roundtrips.
Signed-off-by: squat <lserven@gmail.com>

feat: increase keepalive timeout

---

projects/fal/src/fal/app.py

The logs are printed raw right now, but I'll make them comply with the normal styling a followup. This is useful as is and allows for easier testing.

feat(AppClient): support timeout and print logs

---

projects/fal/tests/test_apps.py

since we added a timeout on the server side to get logs, this may fail some times

ci: add retry for failing test

---

projects/fal/src/fal/app.py
projects/fal/src/fal/cli/deploy.py
projects/fal/src/fal/cli/run.py
projects/fal/src/fal/utils.py

SDK part of the deal of addressing confusion when people click on their deployed app URL and see 404 because it doesn't have a root endpoint.

feat(deploy): show available endpoints

---

projects/fal/src/fal/__main__.py

Kudos @badayvedat for reporting this.

fix(fal): don't forget to sys.exit when running as a module

---

projects/fal/src/fal/cli/_utils.py
projects/fal/tests/cli/test_deploy.py
projects/fal/tests/cli/test_run.py

Otherwise we would need to know in which directory the command needed to be run

feat(fal-file): convert the app-ref to a path relative to the project root

---

projects/fal/src/fal/cli/_utils.py
projects/fal/src/fal/cli/deploy.py
projects/fal/src/fal/cli/run.py
projects/fal/tests/cli/test_deploy.py

makes it possible to pass deployment strategy in the fal file, example:
```toml
[tool.fal.apps.my-app]
ref = "src/my-app/inference.py::MyApp"
auth = "private"
deployment_strategy = "rolling"
```

feat(fal-file): add deployment strategy

---

projects/fal_client/src/fal_client/client.py

Part of #180 , fal changes are going to be in a separate PR.
closes #180

feat(fal_client): better client errors

---

projects/fal/src/fal/toolkit/file/file.py
projects/fal/src/fal/toolkit/file/providers/fal.py
projects/fal/src/fal/toolkit/file/types.py
projects/fal/tests/test_stability.py

Straight-up v1 code copied and adapted to support v3 auth.
This allows us to start testing v3 out.
Multipart will be introduced separately.
We also change default lifecycle policy here to never expire, as that seemed to be the conclusion of our recent conversation about it. Note that we still set it for v1 too, but v1 is ignoring those.

feat(toolkit): introduce fal_v3 repository

---

projects/fal_client/src/fal_client/client.py
projects/fal_client/tests/test_async_client.py
projects/fal_client/tests/test_sync_client.py

Allows creating a handle later, in a separate thread/process/etc if the original handle is no longer available.

feat(client): support creating a handle from request_id

---

projects/fal/src/fal/toolkit/file/providers/fal.py
projects/fal/src/fal/toolkit/file/providers/gcp.py
projects/fal/src/fal/toolkit/file/providers/r2.py

Kudos @Gothos for reporting the issue with gcp.save.

fix(toolkit): fix lifecycle in r2/gcp

---

projects/fal/src/fal/app.py

This message is not really critical, so we can just debug() it and not scare users with a traceback.

fix(app): use debug() for label error

---

projects/fal/src/fal/toolkit/image/__init__.py

fixes conflicts between two distinct Request classes.
```py
from urllib.request import Request, urlopen # this one has  a Request from urllib
from .image import *  # noqa: F403 # this one has a Request from fastapi
....
request = Request(url, headers=TEMP_HEADERS) 
```

fix(image-toolkit): request class conflict

---

projects/fal/pyproject.toml

1. Avoid jumping breaking versions of isolate
2. Include a bump to minimum 0.14.2

fix: proper isolate version check

---

projects/fal/src/fal/app.py

This is important so logs are sent in an accurate time

fix: flush before setting logger labels

---

.github/workflows/integration_tests.yaml
.github/workflows/tests-fal-client.yml
projects/fal/src/fal/apps.py
projects/fal/src/fal/workflows.py
projects/fal/tests/cli/test_deploy.py
projects/fal/tests/cli/test_run.py
projects/fal/tests/test_apps.py
projects/fal_client/src/fal_client/client.py

fix: support 3.8 to 3.12 for fal and fal-client

---

projects/fal/src/fal/app.py

fix: make request_id logging label be present during entire request stream

---

projects/fal/src/fal/apps.py

We are leaving the task of parsing to the user
This makes sense to not do too much magic and then it gets hard to mantain.

feat: handle stream correctly

---

projects/fal/src/fal/app.py
projects/fal/src/fal/toolkit/file/file.py
projects/fal/src/fal/toolkit/file/providers/fal.py

1. no longer default to 1 day
2. tries to use the request's headers almost always

fix: remove default object lifecycle for CDN and use header when possible

---

projects/fal/pyproject.toml
projects/fal/src/fal/container.py
projects/fal/tests/cli/test_deploy.py
projects/fal/tests/cli/test_run.py
projects/fal/tests/conftest.py
projects/fal/tests/integration_test.py
projects/fal/tests/test_apps.py
projects/fal/tests/test_stability.py
projects/fal/tests/toolkit/file_test.py
projects/fal/tests/toolkit/image_test.py
projects/fal/tests/toolkit/utils/retry.py

We currently do not exercise container apps in our tests, the container
app seems to be an unused fixture. This commit introduces basic tests to
ensure that container apps are built and work as expected. Furthermore,
this commit introduces a check that container args actually work.
Finally, this commit removes the `build_env` keyword from the
`ContainerImage` class. Docker has no concept of specifying environment
variables at build time except by declaring build arguments. Having that
keyword is messy and opens the door to non-hermetic builds, which is
a recipe for leaks and reproducibility problems.
Signed-off-by: squat <lserven@gmail.com>

misc(container): add tests for container apps and remove build_env

---

projects/fal/src/fal/app.py
projects/fal/src/fal/auth/__init__.py

Adapting #377 to work with sdk as well.
Kudos @not-lain

feat(fal/auth): add support for Google Colab token retrieval

---

projects/fal/src/fal/toolkit/types.py
projects/fal/tests/toolkit/test_types.py

Proposed  Interface
```py
import os
from pydantic import BaseModel
from fal.toolkit.types import FileInput, ImageInput
class Input(BaseModel):
image: ImageInput
file: FileInput
a = Input(
image="https://storage.googleapis.com/falserverless/model_tests/remove_background/elephant.jpg",
file="https://raw.githubusercontent.com/fal-ai/fal/refs/heads/main/README.md"
)
with a.image.as_temp_file() as file_path:
print(file_path)
pil_image = a.image.to_pil()
print(pil_image)
with a.file.as_temp_file() as file_path:
print(file_path)
```

feat(toolkit): input types

---

projects/fal/src/fal/api.py
projects/fal/src/fal/auth/__init__.py
projects/fal/src/fal/config.py
projects/fal/tests/integration_test.py
projects/fal/tests/toolkit/image_test.py

Currently one needs to either `login` or keep using `FAL_KEY` env vars either implicitly or explicitly, but both can lead to confusion. In my case I find myself generating new keys all the time, because I can't remember which one was which. This PR introduces
* `~/.fal/config.toml` or `FAL_CONFIG_PATH` with profile sections
* `FAL_PROFILE` to set particular profile
which allows keeping keys in one place and then easily switching between them, similar to tools like aws cli or modal.
In the future we can also use this for acquiring list of teams that your account has access to and switching between them, similar to `modal profile`.

feat(fal): support basic fal profiles

---

projects/fal/src/fal/toolkit/utils/download_utils.py
projects/fal/tests/integration_test.py

This mitigates a situation when there are two apps that both want to clone a repo but with different commits.

feat(toolkit): use sha in resulting repo name to avoid race conditions

---

projects/fal/src/fal/app.py

there is no `NOMAD_ALLOC_PORT_grpc` in this scenario

fix: handle calling req-id setting locally

---

projects/fal/src/fal/toolkit/file/providers/fal.py

Old implementation was moved to `Internal*` prefixed classes and is not used by default because of the long lived tokens, so we need to re-implement it for uploads that go through our rest.

feat(toolkit): support multipart uploads without long-lived tokens

---

projects/fal/src/fal/api.py
projects/fal/src/fal/container.py

One rarely needs a gpu to be present during dockerfile build, so there is no reason to waste resources on that.
Current logic builds on worker if you ask for GPU machine_type (which is most of the time) and if not tries to build in `service` without GPU. This PR makes that explicit and defined on the sdk-side instead of backend.

feat(fal): rework container support and make depot default

---

projects/fal/src/fal/toolkit/utils/download_utils.py

Semi-atomically rename to a temp dir and then delete to avoid race conditions.

fix(toolkit): rename to a tmp dir before deleting

---

projects/fal/pyproject.toml
projects/fal/src/fal/api.py
projects/fal/src/fal/app.py
projects/fal/src/fal/sdk.py

Pre-requisite https://github.com/fal-ai/isolate-cloud/pull/3061

feat(fal): introduce startup_timeout

---

projects/fal/src/fal/toolkit/file/file.py

`cdn` just like `fal_v3` are cloudflare-based, so if r2 or cf have an outage they will both go down. `fal` is our own legacy one that had the same feature parity as `cdn` (lacking object lifecycle, multipart) but still useful for now.

feat(toolkit): fallback to `fal` instead of `cdn`

---

projects/fal/src/fal/cli/apps.py

feat: print number of runners and requests on "app runners"

---

projects/fal/pyproject.toml
projects/fal/src/fal/cli/main.py
projects/fal/src/fal/cli/profile.py
projects/fal/src/fal/config.py

feat: add profile management cli

---

projects/fal/tests/test_apps.py

This is the app we test logs for and we want it to have the full fal.App functionality of setting `request_id` in logs and more

ci: use fal.App for addition app

---

projects/fal/pyproject.toml
projects/fal/src/fal/api.py
projects/fal/src/fal/cli/apps.py
projects/fal/src/fal/cli/deploy.py
projects/fal/src/fal/sdk.py
projects/fal/tests/cli/test_apps.py

Also, add a column to display runners with missing leases (=zombies)

feat: show concurrency_buffer when listing apps and allow adjusting it

---

projects/fal/tests/test_apps.py

sometimes it can take up to 30 seconds to start an app

fix(ci): more reliable request cancellation test

---

projects/fal/src/fal/auth/__init__.py
projects/fal/src/fal/cli/_utils.py
projects/fal/src/fal/cli/apps.py
projects/fal/src/fal/cli/auth.py
projects/fal/src/fal/cli/keys.py
projects/fal/src/fal/cli/main.py
projects/fal/src/fal/cli/parser.py
projects/fal/src/fal/cli/profile.py
projects/fal/src/fal/cli/runners.py
projects/fal/src/fal/cli/secrets.py
projects/fal/src/fal/cli/teams.py
projects/fal/src/fal/config.py
projects/fal/src/fal/sdk.py

E.g. `fal apps list --team myteamnickname`
`fal auth login` will now suggest setting a team you want to use right away. E.g.
```
(fal-3.11.9) MacBook-Pro-2.local ➜  fal git:(ruslan/user-teams) ✗  fal auth login                
Please choose a team account to use or leave blank to use your personal account: 
[team1/team2/team3]: team1
Setting team to team1. You can change this later with fal teams.
```

feat(fal): support teams

---

projects/fal/src/fal/app.py
projects/fal/src/fal/cli/deploy.py
projects/fal/src/fal/sdk.py
projects/fal/tests/test_apps.py

```
❯ fal deploy t/bbasic.py
✘ Must specify auth_mode
❯ set -x FAL_KEY ...
❯ fal deploy t/bbasic.py
Registered a new revision for function 'basic' (revision='a8e620e1-24b5-4f11-9d26-200846e4cd76').
...
```
TODO:

fix: stop defaulting auth mode to private locally

---

projects/fal/src/fal/auth/__init__.py
projects/fal/src/fal/cli/auth.py
projects/fal/src/fal/cli/teams.py
projects/fal/src/fal/sdk.py

Made fal team list and set work the same as the auth login experieince
Also auth login had errors in variables not existing and files not existing
```
❯ fal auth login
If browser didn't open automatically, on your computer or mobile device navigate to
https://auth.fal.ai/v2/...
Confirm it shows the following code: 1234-1234
✓ Authenticated successfully, welcome!
┌──────┬───────────────────────────┬──────────┐
│   1  │ chamini2                  │ Personal │
│   2  │ Matteos-Team              │ Team     │
│   3  │ ayyy                      │ Team     │
└──────┴───────────────────────────┴──────────┘
Select an account by number: 0
Please select one of the available options
Select an account by number: 1
Using personal account chamini2
```
```
❯ fal team list …
```

fix: make team selection consistent, fix auth login error, and implement auth whomai

---

projects/fal/src/fal/cli/profile.py
projects/fal/src/fal/config.py

```
(fal-3.11.9) MacBook-Pro-2.local ➜  fal git:(ruslan/fix-unset) ✗  fal profile unset --pdb
> /Users/efiop/git/efiop/fal/projects/fal/src/fal/config.py(88)set_internal()
-> del self._config[SETTINGS_SECTION][key]
(Pdb) l
83         def set_internal(self, key: str, value: Optional[str]) -> None:
84             if SETTINGS_SECTION not in self._config:
85                 self._config[SETTINGS_SECTION] = {}
86  
87             if value is None:
88  ->             del self._config[SETTINGS_SECTION][key]
89             else:
90                 self._config[SETTINGS_SECTION][key] = value
91  
92         def delete(self, profile: str) -> None:
93             del self._config[profile]
(Pdb) key
'profile'
```

fix(profile): use unset_internal

---

projects/fal/src/fal/api.py

For better resource management and so that we don't have to try to pickle it if something accidentally imports one of the source files.

chore: remove global thread pool

---

projects/fal/src/fal/api.py
projects/fal/src/fal/app.py
projects/fal/src/fal/logging/isolate.py
projects/fal/src/fal/sdk.py

Misc cleanups like global object removals and lazy imports. Cloudpickle by-reference pickling for fal module is having trouble with tricky imports.

fix: cleanup global objects/imports for safer pickling

---

projects/fal/src/fal/exceptions/_cuda.py
projects/fal/tests/test_apps.py

CUDA OOM could sometimes look like
```
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":830, please report a bug to PyTorch. 
```
See https://github.com/pytorch/pytorch/issues/112377

fix: handle NVML_SUCCESS == r INTERNAL ASSERT FAILED

---

projects/fal_client/pyproject.toml
projects/fal_client/src/fal_client/client.py
projects/fal_client/tests/test_async_client.py
projects/fal_client/tests/test_sync_client.py

Covers all of these
```
TimeoutException
ConnectTimeout
ReadTimeout
WriteTimeout
PoolTimeout
NetworkError
ConnectError
ReadError
WriteError
CloseError
ProtocolError
LocalProtocolError
RemoteProtocolError
ProxyError
UnsupportedProtocol
```

feat(fal_client): retry on httpx.TransportError

---

projects/fal/src/fal/cli/_utils.py
projects/fal/src/fal/project.py

Making space for the upcoming fal app files feature. These are all purely utilities so no reason to take up `fal.files`

chore: rename files.py -> project.py

---

projects/fal/src/fal/cli/auth.py
projects/fal/src/fal/cli/teams.py

```
❯ fal profile set some
Default profile set to some.
❯ fal team set my-team
Using team account my-team. You can change this later with fal team set
Unsetting profile fal to make team selection effective.
Default profile unset.
```

chore: set team selected in __internal__ section and automatically clear profile when setting team

---

projects/fal/src/fal/_serialization.py
projects/fal/src/fal/api.py
projects/fal/src/fal/app.py
projects/fal/src/fal/utils.py

Sometimes users just have their own module lying around next to the fal app python file, which makes it tricky for us to detect when they want to include it into their app or how. This introduces a new `App.local_python_modules` that allows you to just tell us which modules you want us to bring together with the app.
For example, say you have this file structure (parent is not a python module):
```
mymodule/
myfalapp.py
```
now you can just
```
from mymodule import mysetup
class MyApp(fal.App, ...):
requirements = ["torch", ...]
local_python_modules = ["mymodule"]
def setup(self):
mysetup()
...
```

feat: introduce local_python_modules

---

projects/fal/src/fal/api.py
projects/fal/src/fal/app.py
projects/fal/tests/test_apps.py

closes FEA-5224
```
❯ fal deploy t/bbasic.py --auth shared
✘ Failed to generate OpenAPI metadata for function: Invalid args for response field! Hint: check that typing.Union[<run_path>.HelloOutput, <run_path>.TextEventStream] is a valid Pydantic field type. If you are using a return type annotation that is not a valid Pydantic field (e.g. Union[Response, dict, None]) you can
disable generating the response model from the type annotation with the path operation decorator parameter response_model=None. Read more: https://fastapi.tiangolo.com/tutorial/response-model/
```

feat: make sure to fail on OpenAPI generation

---

projects/fal/src/fal/toolkit/utils/endpoint.py
projects/fal/tests/test_apps.py

It seems we do not handle disconnects well from the gateway.
This ends up in apps sometimes handling 2 requests at a time.
closes FEA-5223

feat: add cancellation handler

---

projects/fal/src/fal/api.py

The message changed in backend making our heuristic break:
```
06/18/2025 09:04:57 [global] [bridge]   [info]    Access the playground at https://fal.ai/dashboard/sdk/fal-ai/5a2c4b72-ecc8-4fc7-ab0a-bb148bc5df75
06/18/2025 09:04:57 [global] [bridge]   [info]    And API access through https://queue.shark.fal.run/fal-ai/5a2c4b72-ecc8-4fc7-ab0a-bb148bc5df75
```

fix(api): expect a different API url message

---

projects/fal/src/fal/container.py

Allows users to use fal secrets as docker secrets.
```
class MyApp(
fal.App,
kind="container",
image=ContainerImage.from_dockerfile_str(
f"""
FROM ...
RUN --mount=type=secret,id=mysecretid cat /run/secrets/mysecretid
""",
secrets={"mysecretid": "$MY_FAL_SECRET"},
),
):
...
```

feat(container): support secrets

---

projects/fal/src/fal/cli/profile.py
projects/fal/src/fal/config.py

I have found myself making mistakes by always having some profile set. Making it so you _can_ have no profile enabled is a easier to understand experience.
Here we remove the default profile 'default' and we also ask if the user wants to create a new profile when an unknown name is set.
We also offer a `fal profile create <name>` command.
Finally, if no profile is set, `fal profile key` and `fal profile host` will now fail

refactor: profile command remove default profile

---

projects/fal/src/fal/api.py

Simple convenience feature that makes us no longer error out with
```
Unexpected <class 'TypeError'>: VirtualPythonEnvironment.__init__() got an unexpected keyword argument 'image'
```

feat: assume kind=container when image is passed

---

projects/fal/src/fal/toolkit/utils/__init__.py
projects/fal/src/fal/toolkit/utils/setup_utils.py

This PR adds a utility function `patch_onnx_runtime` that ought to be used in fal apps to prevent excess warning logs by onnx runtime.

feat: adds a utility function to patch onnx runtime for fal apps

---

projects/fal/src/fal/console/__init__.py

Prevents broken links in some terminals with small window sizes.

fix(fal): set soft_wrap=True for rich Console

---

projects/fal/src/fal/toolkit/file/providers/fal.py

Currently, token managers are not pickleable, and are defined at the module level.
This means multiprocessing apps must avoid importing them before the fork, or else the app will fail with `TypeError: cannot pickle '_thread.lock' object`.
The simple solution is to enable them to be pickleable by not trying to pickle the lock object, and letting each process have their own lock. An alternative solution could be to use a multiprocessing lock, but I think the overhead there wouldn't be worth it - typically only one process (the rank 0 process) will be uploading anyway.

Fix: make token managers pickleable

---

projects/fal/src/fal/auth/__init__.py

As a follow-up from https://github.com/fal-ai/fal/pull/632 - tracing revealed there was one more global lock that tried to pickle after the token manager did.
I did a follow-up trace of `threading.Lock`s anywhere in the SDK, it looks like the only remaining one is on the `FalServerlessHost`, but that is not defined globally so it's not an issue.

Fix: remove last global lock

---

projects/fal/pyproject.toml

https://github.com/fal-ai/fal/pull/637 is not sufficient, since this pr https://github.com/fal-ai/fal/pull/636 uses the new field, we need to make sure the isolate_proto version is at least 0.17

chore: Bump isolate proto min version to 0.17
